### ISSUE TITLE
Problemes a l'enviar mails amb els logs

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#44]
* [ ] Hi ha temes de codificació que s'han de resoldre o no envia els mails correctament
* [ ] Es perden els accents.

<lcfib@bustia.fib.upc.es>: temporary failure. Command output: delivered to
    /home4/users/lcfib/lcfib/nsmail/Backup Traceback (most recent call last):
    File "/home4/users/lcfib/lcfib/mailtoticket/mailtoticket.py", line 49, in
    <module>     correu.enviar(buffer.getvalue())   File
    "/home4/users/lcfib/lcfib/mailtoticket/correu.py", line 11, in enviar
    server.sendmail(de, a, msg)   File "/usr/lib64/python2.5/smtplib.py", line
    696, in sendmail     (code,resp) = self.data(msg)   File
    "/usr/lib64/python2.5/smtplib.py", line 493, in data     self.send(q)
    File "/usr/lib64/python2.5/smtplib.py", line 320, in send
    self.sock.sendall(str)   File "<string>", line 1, in sendall
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in
    position 250: ordinal not in range(128) /home/soft/maildrop/bin/maildrop:
    Unable to filter message.

**Comment by jaumemoral** [comment]
S'ha de buscar un dels mails que ho fa fallat i fer un "cat" al mailtoticket per veure si peta. Segurament es podrà solucionar enviant com a mime o fent un text.encode('ascii').

**Comment by jaumemoral** [comment]
Solucionat. Ara ja no peta i a més no té problemes amb els accents del subject.

**Comment by jaumemoral** [comment]
Aixo ara esta implementat de forma diferent i ja no tenim problemes d'encoding
