### ISSUE TITLE
Dona error quan intenta tractar un mail amb un mail adjuntat

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#58]
L'error sembla relacionat amb que intenta tractar "parts" del mail que realment son contenidors d'altres parts

Ha petat algun dels filtres i no marco el mail com a tractat
Traceback (most recent call last):
  File "/home2/users/lcfib/ticket-personal/mailtoticket/mailtoticket.py", line 39, in <module>
    if filtres.aplicar_filtres(mail):
  File "/home2/users/lcfib/ticket-prisma/mailtoticket/filtres/__init__.py", line 45, in aplicar_filtres
    tractat=filtre.filtrar()
  File "/home2/users/lcfib/ticket-prisma/mailtoticket/filtres/nou.py", line 59, in filtrar
    descripcio=self.afegir_attachments_canviant_body(ticket_id,self.solicitant,descripcio)
  File "/home2/users/lcfib/ticket-prisma/mailtoticket/filtres/filtre.py", line 45, in afegir_attachments_canviant_body
    (cids,ids)=self.afegir_attachments(ticket_id,username)
  File "/home2/users/lcfib/ticket-prisma/mailtoticket/filtres/filtre.py", line 63, in afegir_attachments
    codi_annex=self.tickets.annexar_fitxer_tiquet(ticket_id,username,fitxer, self.codificar_base_64_si_cal(a))
  File "/home2/users/lcfib/ticket-prisma/mailtoticket/filtres/filtre.py", line 42, in codificar_base_64_si_cal
    return base64.b64encode(attachment.get_payload())
  File "/home/soft/python/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be string or buffer, not list

**Comment by jaumemoral** [comment]
Solucionat. He fet que consideri que un attachment no es valid quan es multipart.

El "problema" es que la funcio walk() que es pateja totes les parts d'un mail, també itera sobre les que no son estrictament fulles. Aixo provoca que consideri un attachment algo que realment no es mes que un contenidor d'altres parts, que son les que realment cal posar com a attachment.

Tal i com està ara segurament deixa mes coses com a attachment de les que toquen, pero millor que n'hi hagi de mes que no de menys.
